#include "ebpf_collector.h"
#include "bpf_shared_maps.h"
#include "logger.h"
#include "tcpsnitch.skel.h" //Generated by: bpftool gen skeleton

#include <bpf/bpf.h>
#include <bpf/libbpf.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

/* ── Internal State ──────────────────────────────────────────────────────── */

static struct {
    struct tcpsnitch_bpf *skel;
    struct ring_buffer *rb;
    int map_fd;
    int sport_map_fd;
    FILE *jsonl_fp;
    pthread_t thread;
    bool active;
    bool stop_flag;
    pthread_mutex_t file_mutex;
} g_collector = {
    .skel = NULL,
    .rb = NULL,
    .map_fd = -1,
    .sport_map_fd = -1,
    .jsonl_fp = NULL,
    .active = false,
    .stop_flag = false,
    .file_mutex = PTHREAD_MUTEX_INITIALIZER,
};

/* ── JSONL Serialization ─────────────────────────────────────────────────── */

static void write_event_jsonl(const struct ebpf_event *ev) {
    if (!g_collector.jsonl_fp)
        return;

    const char *type_str;
    switch (ev->type) {
    case EBPF_EV_TCP_RETRANSMIT:
        type_str = "tcp_retransmit";
        break;
    case EBPF_EV_IOURING_COMPLETE:
        type_str = "iouring_complete";
        break;
    case EBPF_EV_MPTCP_SUBFLOW:
        type_str = "mptcp_subflow";
        break;
    default:
        type_str = "unknown";
        break; // Sécurité
    }

    pthread_mutex_lock(&g_collector.file_mutex);

    fprintf(g_collector.jsonl_fp,
            "{\"source\":\"ebpf\","
            "\"type\":\"%s\","
            "\"session_id\":%" PRIu64 ","
            "\"timestamp_ns\":%" PRIu64 ","
            "\"pid\":%" PRIu32 ",",
            type_str, (uint64_t)ev->session_id, (uint64_t)ev->timestamp_ns,
            (uint32_t)ev->pid);

    switch (ev->type) {
    case EBPF_EV_TCP_RETRANSMIT:
        fprintf(g_collector.jsonl_fp,
                "\"seq\":%" PRIu32 ","
                "\"snd_cwnd\":%" PRIu32 ","
                "\"srtt_us\":%" PRIu32,
                (uint32_t)ev->tcp_retransmit.seq,
                (uint32_t)ev->tcp_retransmit.snd_cwnd,
                (uint32_t)ev->tcp_retransmit.srtt_us);
        break;

    case EBPF_EV_IOURING_COMPLETE:
        fprintf(g_collector.jsonl_fp,
                "\"user_data\":%" PRIu64 ","
                "\"res\":%" PRId32,
                (uint64_t)ev->iouring_complete.user_data,
                (int32_t)ev->iouring_complete.res);
        break;

    case EBPF_EV_MPTCP_SUBFLOW:
        fprintf(g_collector.jsonl_fp,
                "\"token\":%" PRIu32 ","
                "\"family\":%" PRIu8 ","
                "\"is_backup\":%" PRIu8,
                (uint32_t)ev->mptcp_subflow.token,
                (uint8_t)ev->mptcp_subflow.family,
                (uint8_t)ev->mptcp_subflow.is_backup);
        break;
    }

    fprintf(g_collector.jsonl_fp, "}\n");
    pthread_mutex_unlock(&g_collector.file_mutex);
}

/* ── Callbacks & Polling ─────────────────────────────────────────────────── */

static int handle_event(void *ctx, void *data, size_t data_sz) {
    (void)ctx;
    (void)data_sz;
    const struct ebpf_event *ev = (const struct ebpf_event *)data;

    // Skip untracked events (session_id 9999 is a special value for untracked
    // events)
    if (ev->session_id == 9999)
        return 0;

    write_event_jsonl(ev);
    return 0;
}

static void *polling_thread(void *arg) {
    (void)arg;
    LOG(INFO, "eBPF collector polling thread started.");

    while (!g_collector.stop_flag) {
        int n = ring_buffer__poll(g_collector.rb, 100 /* ms */);
        if (n < 0 && n != -EINTR) {
            LOG(ERROR, "ring_buffer__poll() failed: %s", strerror(-n));
            break;
        }
    }

    pthread_mutex_lock(&g_collector.file_mutex);
    if (g_collector.jsonl_fp)
        fflush(g_collector.jsonl_fp);
    pthread_mutex_unlock(&g_collector.file_mutex);

    LOG(INFO, "eBPF collector polling thread stopped.");
    return NULL;
}

/* ── Public API ──────────────────────────────────────────────────────────── */

int ebpf_collector_init(const char *output_dir) {
    int ret = 0;

    char jsonl_path[512];
    snprintf(jsonl_path, sizeof(jsonl_path), "%s/ebpf_events.jsonl",
             output_dir);

    g_collector.jsonl_fp = fopen(jsonl_path, "w");
    if (!g_collector.jsonl_fp) {
        LOG(ERROR, "ebpf_collector: fopen(%s) failed: %s", jsonl_path,
            strerror(errno));
        return -1;
    }

    g_collector.skel = tcpsnitch_bpf__open_and_load();
    if (!g_collector.skel) {
        LOG(ERROR, "ebpf_collector: failed to open/load BPF skeleton. "
                   "Ensure kernel >= 5.10 and CAP_BPF or root privileges.");
        ret = -1;
        goto err_close_file;
    }

    int attached = 0;

    g_collector.skel->links.trace_tcp_retransmit =
        bpf_program__attach(g_collector.skel->progs.trace_tcp_retransmit);
    if (g_collector.skel->links.trace_tcp_retransmit) {
        attached++;
    } else {
        LOG(WARN,
            "ebpf_collector: tracepoint tcp_retransmit_skb not found. TCP "
            "retransmissions won't be traced by eBPF.");
    }

    g_collector.skel->links.trace_iouring_complete =
        bpf_program__attach(g_collector.skel->progs.trace_iouring_complete);
    if (g_collector.skel->links.trace_iouring_complete) {
        attached++;
    } else {
        LOG(WARN, "ebpf_collector: tracepoint io_uring_complete not found. "
                  "io_uring won't be traced by eBPF.");
    }

    g_collector.skel->links.trace_mptcp_subflow =
        bpf_program__attach(g_collector.skel->progs.trace_mptcp_subflow);
    if (g_collector.skel->links.trace_mptcp_subflow) {
        attached++;
    } else {
        LOG(INFO,
            "ebpf_collector: MPTCP tracepoint not available on this kernel "
            "(normal).");
    }

    if (attached == 0) {
        LOG(ERROR,
            "ebpf_collector: No tracepoints could be attached. eBPF disabled.");
        ret = -ENOENT;
        goto err_destroy_skel;
    }

    g_collector.sport_map_fd = bpf_map__fd(g_collector.skel->maps.sport_to_session);
    if (g_collector.sport_map_fd < 0) {
        LOG(ERROR, "ebpf_collector: could not get sport_to_session fd.");
        ret = -1; 
        goto err_destroy_skel;
    }

    g_collector.map_fd = bpf_map__fd(g_collector.skel->maps.fd_to_session_map);
    if (g_collector.map_fd < 0) {
        LOG(ERROR, "ebpf_collector: could not get fd_to_session_map fd.");
        ret = -1;
        goto err_destroy_skel;
    }

    g_collector.rb = ring_buffer__new(
        bpf_map__fd(g_collector.skel->maps.events), handle_event, NULL, NULL);
    if (!g_collector.rb) {
        LOG(ERROR, "ebpf_collector: ring_buffer__new() failed.");
        ret = -1;
        goto err_destroy_skel;
    }

    LOG(INFO, "eBPF collector initialized. Output: %s", jsonl_path);
    return 0;

err_destroy_skel:
    tcpsnitch_bpf__destroy(g_collector.skel);
    g_collector.skel = NULL;
err_close_file:
    fclose(g_collector.jsonl_fp);
    g_collector.jsonl_fp = NULL;
    return ret;
}

int ebpf_collector_start(void) {
    if (!g_collector.skel || !g_collector.rb) {
        LOG(WARN, "ebpf_collector_start: collector not initialized, skipping.");
        return -1;
    }

    g_collector.stop_flag = false;
    int ret = pthread_create(&g_collector.thread, NULL, polling_thread, NULL);
    if (ret) {
        LOG(ERROR, "ebpf_collector_start: pthread_create failed: %s",
            strerror(ret));
        return -1;
    }

    g_collector.active = true;
    LOG(INFO, "eBPF collector thread started.");
    return 0;
}

void ebpf_collector_stop(void) {
    if (!g_collector.active)
        return;

    g_collector.stop_flag = true;
    pthread_join(g_collector.thread, NULL);
    g_collector.active = false;

    if (g_collector.rb) {
        ring_buffer__free(g_collector.rb);
        g_collector.rb = NULL;
    }
    if (g_collector.skel) {
        tcpsnitch_bpf__destroy(g_collector.skel);
        g_collector.skel = NULL;
    }

    pthread_mutex_lock(&g_collector.file_mutex);
    if (g_collector.jsonl_fp) {
        fflush(g_collector.jsonl_fp);
        fclose(g_collector.jsonl_fp);
        g_collector.jsonl_fp = NULL;
    }
    pthread_mutex_unlock(&g_collector.file_mutex);

    LOG(INFO, "eBPF collector stopped and resources freed.");
}

bool ebpf_collector_is_active(void) {
    return g_collector.active;
}

/* ── FD Lifecycle Management ─────────────────────────────────────────────── */

void ebpf_collector_register_fd(int fd, uint64_t session_id) {
    if (g_collector.map_fd < 0)
        return;

    struct fd_key key = {
        .pid = (uint32_t)getpid(),
        .fd = (int32_t)fd,
    };

    int ret =
        bpf_map_update_elem(g_collector.map_fd, &key, &session_id, BPF_ANY);
    if (ret)
        LOG(WARN, "ebpf_collector_register_fd: fd=%d failed: %s", fd,
            strerror(errno));
}

void ebpf_collector_register_sport(uint16_t sport, uint64_t session_id) {
    if (g_collector.sport_map_fd < 0)
        return;
    if (bpf_map_update_elem(g_collector.sport_map_fd, &sport, &session_id,
                            BPF_ANY) < 0)
        LOG(WARN, "ebpf_collector: register_sport(%u, %lu) failed: %s", sport,
            session_id, strerror(errno));
}

void ebpf_collector_unregister_sport(uint16_t sport) {
    if (g_collector.sport_map_fd < 0)
        return;
    bpf_map_delete_elem(g_collector.sport_map_fd, &sport);
}

void ebpf_collector_unregister_fd(int fd) {
    if (g_collector.map_fd < 0)
        return;

    struct fd_key key = {
        .pid = (uint32_t)getpid(),
        .fd = (int32_t)fd,
    };

    int ret = bpf_map_delete_elem(g_collector.map_fd, &key);
    if (ret && errno != ENOENT)
        LOG(WARN, "ebpf_collector_unregister_fd: fd=%d failed: %s", fd,
            strerror(errno));
}

void ebpf_collector_dup_fd(int old_fd, int new_fd) {
    if (g_collector.map_fd < 0)
        return;

    uint32_t pid = (uint32_t)getpid();

    struct fd_key old_key = {.pid = pid, .fd = (int32_t)old_fd};
    uint64_t session_id = 0;

    int ret = bpf_map_lookup_elem(g_collector.map_fd, &old_key, &session_id);
    if (ret) {
        return;
    }

    struct fd_key new_key = {.pid = pid, .fd = (int32_t)new_fd};
    ret =
        bpf_map_update_elem(g_collector.map_fd, &new_key, &session_id, BPF_ANY);
    if (ret)
        LOG(WARN, "ebpf_collector_dup_fd: new_fd=%d failed: %s", new_fd,
            strerror(errno));
}